server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}